# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\PYWS\WebCatch\WebCatch-PythonVersion-\MainWindow.ui'
#
# Created: Tue Dec 16 15:18:11 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1205, 443)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("wico.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 751, 25))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.leURL = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.leURL.setObjectName(_fromUtf8("leURL"))
        self.horizontalLayout.addWidget(self.leURL)
        self.btnExct = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnExct.setObjectName(_fromUtf8("btnExct"))
        self.horizontalLayout.addWidget(self.btnExct)
        self.teExctData = QtGui.QTextEdit(Dialog)
        self.teExctData.setGeometry(QtCore.QRect(800, 310, 201, 41))
        self.teExctData.setObjectName(_fromUtf8("teExctData"))
        self.btnConnect = QtGui.QPushButton(Dialog)
        self.btnConnect.setGeometry(QtCore.QRect(800, 200, 101, 23))
        self.btnConnect.setObjectName(_fromUtf8("btnConnect"))
        self.btnSave = QtGui.QPushButton(Dialog)
        self.btnSave.setGeometry(QtCore.QRect(1020, 20, 171, 21))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(800, 290, 111, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.leTablename = QtGui.QLineEdit(Dialog)
        self.leTablename.setGeometry(QtCore.QRect(1100, 50, 91, 20))
        self.leTablename.setObjectName(_fromUtf8("leTablename"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(1030, 50, 71, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 90, 771, 341))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.btnLoad = QtGui.QPushButton(Dialog)
        self.btnLoad.setGeometry(QtCore.QRect(1020, 80, 171, 21))
        self.btnLoad.setObjectName(_fromUtf8("btnLoad"))
        self.teHTMLCode = QtGui.QTextEdit(Dialog)
        self.teHTMLCode.setGeometry(QtCore.QRect(1020, 330, 171, 61))
        self.teHTMLCode.setObjectName(_fromUtf8("teHTMLCode"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(1020, 300, 61, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.btnExtfromCode = QtGui.QPushButton(Dialog)
        self.btnExtfromCode.setGeometry(QtCore.QRect(1020, 400, 171, 21))
        self.btnExtfromCode.setObjectName(_fromUtf8("btnExtfromCode"))
        self.leThreshold = QtGui.QLineEdit(Dialog)
        self.leThreshold.setGeometry(QtCore.QRect(287, 60, 113, 20))
        self.leThreshold.setObjectName(_fromUtf8("leThreshold"))
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(140, 60, 141, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.btnDisConnect = QtGui.QPushButton(Dialog)
        self.btnDisConnect.setGeometry(QtCore.QRect(910, 200, 91, 23))
        self.btnDisConnect.setObjectName(_fromUtf8("btnDisConnect"))
        self.btnCloseCurTab = QtGui.QPushButton(Dialog)
        self.btnCloseCurTab.setGeometry(QtCore.QRect(20, 61, 91, 20))
        self.btnCloseCurTab.setObjectName(_fromUtf8("btnCloseCurTab"))
        self.btnShowTables = QtGui.QPushButton(Dialog)
        self.btnShowTables.setGeometry(QtCore.QRect(1020, 270, 171, 23))
        self.btnShowTables.setObjectName(_fromUtf8("btnShowTables"))
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(1020, 150, 61, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.leDTableName = QtGui.QLineEdit(Dialog)
        self.leDTableName.setGeometry(QtCore.QRect(870, 230, 131, 20))
        self.leDTableName.setObjectName(_fromUtf8("leDTableName"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(800, 230, 61, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.btnDeleteTable = QtGui.QPushButton(Dialog)
        self.btnDeleteTable.setGeometry(QtCore.QRect(800, 260, 201, 23))
        self.btnDeleteTable.setObjectName(_fromUtf8("btnDeleteTable"))
        self.btnAppend = QtGui.QPushButton(Dialog)
        self.btnAppend.setGeometry(QtCore.QRect(1020, 110, 171, 21))
        self.btnAppend.setObjectName(_fromUtf8("btnAppend"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(800, 110, 41, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lePort = QtGui.QLineEdit(Dialog)
        self.lePort.setGeometry(QtCore.QRect(860, 110, 141, 20))
        self.lePort.setObjectName(_fromUtf8("lePort"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(800, 140, 41, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.leDBName = QtGui.QLineEdit(Dialog)
        self.leDBName.setGeometry(QtCore.QRect(860, 140, 141, 20))
        self.leDBName.setObjectName(_fromUtf8("leDBName"))
        self.lePassword = QtGui.QLineEdit(Dialog)
        self.lePassword.setGeometry(QtCore.QRect(860, 80, 141, 20))
        self.lePassword.setEchoMode(QtGui.QLineEdit.Password)
        self.lePassword.setObjectName(_fromUtf8("lePassword"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(800, 80, 61, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(800, 50, 61, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.leUsername = QtGui.QLineEdit(Dialog)
        self.leUsername.setGeometry(QtCore.QRect(860, 50, 141, 20))
        self.leUsername.setObjectName(_fromUtf8("leUsername"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(800, 20, 41, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.leHost = QtGui.QLineEdit(Dialog)
        self.leHost.setGeometry(QtCore.QRect(860, 20, 141, 20))
        self.leHost.setObjectName(_fromUtf8("leHost"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(800, 170, 138, 29))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lbState = QtGui.QLabel(Dialog)
        self.lbState.setGeometry(QtCore.QRect(940, 170, 71, 29))
        self.lbState.setObjectName(_fromUtf8("lbState"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(800, 369, 36, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.leRowId = QtGui.QLineEdit(Dialog)
        self.leRowId.setGeometry(QtCore.QRect(840, 370, 51, 20))
        self.leRowId.setObjectName(_fromUtf8("leRowId"))
        self.btnDelRow = QtGui.QPushButton(Dialog)
        self.btnDelRow.setGeometry(QtCore.QRect(900, 370, 51, 23))
        self.btnDelRow.setObjectName(_fromUtf8("btnDelRow"))
        self.btnAddRow = QtGui.QPushButton(Dialog)
        self.btnAddRow.setGeometry(QtCore.QRect(950, 370, 51, 23))
        self.btnAddRow.setObjectName(_fromUtf8("btnAddRow"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(800, 400, 36, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.leColId = QtGui.QLineEdit(Dialog)
        self.leColId.setGeometry(QtCore.QRect(840, 400, 51, 20))
        self.leColId.setObjectName(_fromUtf8("leColId"))
        self.btnDelCol = QtGui.QPushButton(Dialog)
        self.btnDelCol.setGeometry(QtCore.QRect(900, 400, 51, 23))
        self.btnDelCol.setObjectName(_fromUtf8("btnDelCol"))
        self.btnAddCol = QtGui.QPushButton(Dialog)
        self.btnAddCol.setGeometry(QtCore.QRect(950, 400, 51, 23))
        self.btnAddCol.setObjectName(_fromUtf8("btnAddCol"))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(470, 60, 78, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.leCurTableName = QtGui.QLineEdit(Dialog)
        self.leCurTableName.setGeometry(QtCore.QRect(560, 60, 131, 20))
        self.leCurTableName.setObjectName(_fromUtf8("leCurTableName"))
        self.btnChangeTName = QtGui.QPushButton(Dialog)
        self.btnChangeTName.setGeometry(QtCore.QRect(700, 60, 71, 21))
        self.btnChangeTName.setObjectName(_fromUtf8("btnChangeTName"))
        self.listTables = QtGui.QListWidget(Dialog)
        self.listTables.setGeometry(QtCore.QRect(1020, 170, 171, 91))
        self.listTables.setObjectName(_fromUtf8("listTables"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "WebExtraction v0.3 beta by 血与光辉@HIT", None))
        self.label.setText(_translate("Dialog", "URL:", None))
        self.leURL.setText(_translate("Dialog", "http://www.converse.com.cn/men.htm?iid=tpnvm0912001&source=topnav", None))
        self.btnExct.setText(_translate("Dialog", "Extract", None))
        self.btnConnect.setText(_translate("Dialog", "Connect", None))
        self.btnSave.setText(_translate("Dialog", "Save the Data into Mysql", None))
        self.label_10.setText(_translate("Dialog", "Console:", None))
        self.leTablename.setText(_translate("Dialog", "table0", None))
        self.label_11.setText(_translate("Dialog", "TableName:", None))
        self.btnLoad.setText(_translate("Dialog", "Load the Data from Mysql", None))
        self.label_15.setText(_translate("Dialog", "HTML Code:", None))
        self.btnExtfromCode.setText(_translate("Dialog", "Extract from HTMLCode", None))
        self.leThreshold.setText(_translate("Dialog", "10", None))
        self.label_16.setText(_translate("Dialog", "threshold(minval is 0):", None))
        self.btnDisConnect.setText(_translate("Dialog", "DisConnect", None))
        self.btnCloseCurTab.setText(_translate("Dialog", "CloseCurTab", None))
        self.btnShowTables.setText(_translate("Dialog", "Show Tables", None))
        self.label_18.setText(_translate("Dialog", "Tables:", None))
        self.label_13.setText(_translate("Dialog", "TableName:", None))
        self.btnDeleteTable.setText(_translate("Dialog", "Delete Table", None))
        self.btnAppend.setText(_translate("Dialog", "Append the Data into Mysql", None))
        self.label_7.setText(_translate("Dialog", "PORT:", None))
        self.lePort.setText(_translate("Dialog", "3306", None))
        self.label_6.setText(_translate("Dialog", "DBName:", None))
        self.leDBName.setText(_translate("Dialog", "test", None))
        self.lePassword.setText(_translate("Dialog", "6191162", None))
        self.label_5.setText(_translate("Dialog", "PassWord:", None))
        self.label_4.setText(_translate("Dialog", "UserName:", None))
        self.leUsername.setText(_translate("Dialog", "root", None))
        self.label_3.setText(_translate("Dialog", "Host:", None))
        self.leHost.setText(_translate("Dialog", "localhost", None))
        self.label_8.setText(_translate("Dialog", "MYSQL Connection State:", None))
        self.lbState.setText(_translate("Dialog", "Unconnected", None))
        self.label_9.setText(_translate("Dialog", "RowId:", None))
        self.btnDelRow.setText(_translate("Dialog", "Delete", None))
        self.btnAddRow.setText(_translate("Dialog", "AddRow", None))
        self.label_12.setText(_translate("Dialog", "ColId:", None))
        self.btnDelCol.setText(_translate("Dialog", "Delete", None))
        self.btnAddCol.setText(_translate("Dialog", "AddCol", None))
        self.label_17.setText(_translate("Dialog", "CurTableName:", None))
        self.btnChangeTName.setText(_translate("Dialog", "Change", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

